# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\"0\n\x10InferenceRequest\x12\r\n\x05input\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x05\"2\n\x11InferenceResponse\x12\x0e\n\x06output\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x03(\x05\x32\x44\n\x10InferenceService\x12\x30\n\x07Predict\x12\x11.InferenceRequest\x1a\x12.InferenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_INFERENCEREQUEST']._serialized_start=19
  _globals['_INFERENCEREQUEST']._serialized_end=67
  _globals['_INFERENCERESPONSE']._serialized_start=69
  _globals['_INFERENCERESPONSE']._serialized_end=119
  _globals['_INFERENCESERVICE']._serialized_start=121
  _globals['_INFERENCESERVICE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
